apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend
  namespace: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook-frontend
  template:
    metadata:
      labels:
        app: guestbook-frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/google-samples/gb-frontend:v5
          ports:
            - containerPort: 80
          env:
            - name: GET_HOSTS_FROM
              value: dns
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
  namespace: guestbook
spec:
  selector:
    app: guestbook-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
