apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
  namespace: guestbook
spec:
  selector:
    app: guestbook-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
